server:
  port: 8010
admin:
  id: ${ADMIN_ID:1234}
  pw: ${ADMIN_PW:1234}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz-quiz?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${PW:}

  jpa:
    open-in-view: false
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update